import React, {useMemo, useState} from 'react';
import styles from './styles.module.css';

const ICON_NAMES = [
  'Accept-email',
  'Ad-product',
  'Add-mode-filled',
  'Add-one',
  'Add-picture',
  'Add-three',
  'Aiming',
  'Align-text-both',
  'Align-text-center',
  'Align-text-left',
  'Align-text-right',
  'All-application',
  'Alphabetical-sorting',
  'Alphabetical-sorting-two',
  'Application',
  'Application-filled',
  'Application-menu',
  'Application-two',
  'Arrow-circle-down',
  'Arrow-circle-left',
  'Arrow-circle-right',
  'Arrow-circle-up',
  'At-sign',
  'Attention',
  'Back-one',
  'Background-color',
  'Bank-card',
  'Bank-card-one',
  'Bolt-one',
  'Bookmark',
  'Bookmarked',
  'Box',
  'Calendar',
  'Camera',
  'Caution',
  'Caution-filled',
  'Chart-line',
  'Chart-pie',
  'Chart-pie-filled',
  'Chat',
  'Chat-filled',
  'Check',
  'Check-correct',
  'Check-one',
  'Check-one-filled',
  'Check-small',
  'Close',
  'Close-one',
  'Close-search',
  'Close-small',
  'Code',
  'Color-card',
  'Column',
  'Comment-filled',
  'Corner-up-left',
  'Corner-up-right',
  'Cut',
  'Cylinder',
  'Delete',
  'Delete-two',
  'Desktop-screen',
  'Double-down',
  'Double-left',
  'Double-right',
  'Double-up',
  'Down',
  'Down-c',
  'Down-small',
  'Download',
  'Download-three',
  'Download-three-filled',
  'Download-one',
  'Drag',
  'Edit',
  'Edit-filled',
  'Electric-drill',
  'Emoji',
  'Euro-outlined',
  'Excel-one-filled',
  'Excel-one',
  'Expand-left',
  'Expand-right',
  'Export',
  'Eyedropper',
  'Facebook',
  'Figma-component',
  'Filter',
  'Find',
  'Fire-extinguisher',
  'Frame-one',
  'Gas',
  'Go-ahead',
  'Go-on',
  'Graphic-design',
  'Hamburger-button',
  'Handle',
  'Headset-one',
  'Health',
  'Heart-rate',
  'Help',
  'History',
  'Home',
  'Id-card-h',
  'Import',
  'Import-and-export',
  'Indent-left',
  'Indent-right',
  'Info',
  'Infusion',
  'Iphone',
  'Left',
  'Left-c',
  'Left-small',
  'Left-small-down',
  'Left-small-up',
  'Lightning',
  'Lightning-fill',
  'Like',
  'Link',
  'Link-filled',
  'Link-two',
  'List-two',
  'List-checkbox',
  'List-numbers',
  'Loading',
  'Lock',
  'Login',
  'Logout',
  'Lung',
  'Magic',
  'Magic-wand',
  'Mail',
  'Mail-download',
  'Mail-open',
  'Medical-box',
  'Medication-time',
  'Message-emoji',
  'Message-one',
  'Minus',
  'Minus-the-top',
  'Moon',
  'Moon-filled',
  'More',
  'More-one',
  'More-three',
  'More-two',
  'Notification',
  'Paperclip',
  'Parallel-gateway',
  'People-top-card',
  'Percentage',
  'Pesticide',
  'Phone-call',
  'Phone-telephone',
  'Picture-one',
  'Pin',
  'Pin-filled',
  'Plus',
  'Preview-close',
  'Preview-close-one',
  'Preview-open',
  'Printer',
  'Printer-filled',
  'Protect-filled',
  'Pull',
  'Pure-natural',
  'Pushpin',
  'Reduce-one',
  'Refresh',
  'Refresh-one-filled',
  'Refresh-one',
  'Reply',
  'Return',
  'Right',
  'Right-c',
  'Right-small',
  'Right-small-down',
  'Right-small-up',
  'Row',
  'Save',
  'Search',
  'Send',
  'Send-email',
  'Setting-config',
  'Setting-filled',
  'Setting-two',
  'Shop',
  'Shopping',
  'Shopping-bag',
  'Shopping-cart-one',
  'Social-apple',
  'Social-discord',
  'Social-facebook',
  'Social-google',
  'Social-instagram',
  'Social-linkedin',
  'Social-mailchimp',
  'Social-messenger',
  'Social-paypal',
  'Social-pinterest',
  'Social-play-store',
  'Social-shopify',
  'Social-spotify',
  'Social-tiktok',
  'Social-twitch',
  'Social-vimeo',
  'Social-whatsapp',
  'Social-windows',
  'Social-x-twitter',
  'Social-youtube',
  'Sort',
  'Sort-alt',
  'Sort-amount-down',
  'Sort-amount-up',
  'Sort-one',
  'Sort-three',
  'Star',
  'Star-2',
  'Star-2-filled',
  'Star-2-half-filled',
  'Success',
  'Sun-1',
  'Sun-filled',
  'Sun-one',
  'Switch',
  'Table-report',
  'Table-report-filled',
  'Tag',
  'Tag-one',
  'Text-bold',
  'Text-italic',
  'Text-underline',
  'Time',
  'Tips-one',
  'To-top',
  'Transfer-data',
  'Translate',
  'Translation',
  'Triangle-round-rectangle',
  'Truck',
  'Undo',
  'Unlock',
  'Up',
  'Up-c',
  'Up-small',
  'Upload',
  'Upload-one',
  'User-business',
  'User-placeholder',
  'Video-two',
  'View-grid-list',
  'Watchdog',
  'Watchdog-filled',
  'Write',
  'Writting-flueantly-filled',
  'Youtube',
  'Zoom-in',
  'Zoom-out',
];

const ICON_BASE_URL =
  'https://raw.githubusercontent.com/SmartBase-SK/django-smartbase-admin/main/src/django_smartbase_admin/static/sb_admin/sprites/sb_admin';

function getIconUrl(iconName) {
  return `${ICON_BASE_URL}/${encodeURIComponent(iconName)}.svg`;
}

export default function IconCatalog() {
  const [query, setQuery] = useState('');

  const filteredIcons = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    if (!normalized) {
      return ICON_NAMES;
    }

    return ICON_NAMES.filter((iconName) =>
      iconName.toLowerCase().includes(normalized),
    );
  }, [query]);

  return (
    <div>
      <div className={styles.toolbar}>
        <input
          type="search"
          className={styles.searchInput}
          placeholder="Filter icons by name..."
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          aria-label="Filter icons by name"
        />
        <div className={styles.resultCount}>
          Showing {filteredIcons.length} of {ICON_NAMES.length} icons
        </div>
      </div>

      <div className={styles.grid}>
        {filteredIcons.map((iconName) => (
          <div key={iconName} className={styles.card}>
            <div className={styles.preview}>
              <img
                src={getIconUrl(iconName)}
                alt={iconName}
                className={styles.image}
                loading="lazy"
              />
            </div>
            <code className={styles.name}>{iconName}</code>
          </div>
        ))}
      </div>
    </div>
  );
}
