# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Django Smartbase Admin
site_url: http://admindocs.sbdev.sk/
repo_url: https://github.com/SmartBase-SK/django-smartbase-admin
theme:
  name: material
  palette:
    accent: grey
nav:
  - 'Home': 'index.md'
  - 'Quickstart': 'quickstart.md'
  - 'Dashboard functions': 'dashboard_functions.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences